import type { Config } from "tailwindcss";

/**
 * FreelancersBix design tokens — deep green x cream x charcoal brand theme.
 *
 * Spacing, fontSize and radius scales are carried over from the approved
 * Stitch export; colors and typography are re-themed to the brand palette
 * (primary #0D5F40, signal-green #167A52, cream surfaces, charcoal ink).
 * Semantic tokens: `primary` = deep green, `whiteout` = card/on-dark text
 * only, `brand-deep` = dark section background.
 */
const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./lib/**/*.{ts,tsx}", "./data/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // FreelancersBix brand system — deep green x cream x charcoal.
        surface: "#FBF8F1",
        "surface-dim": "#F2ECDF",
        "surface-bright": "#FFFFFF",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#FBF8F1",
        "surface-container": "#F6F0E4",
        "surface-container-high": "#F1EADC",
        "surface-container-highest": "#EBE3D1",
        "surface-variant": "#F1EADC",
        "surface-tint": "#167A52",
        background: "#FBF8F1",
        "on-background": "#202722",
        "on-surface": "#202722",
        "on-surface-variant": "#4C5449",
        primary: "#0D5F40",
        "on-primary": "#FBF8F1",
        "primary-container": "#DCEAE1",
        "on-primary-container": "#08452F",
        "primary-fixed": "#DCEAE1",
        "primary-fixed-dim": "#BFDBC9",
        "on-primary-fixed": "#08452F",
        "on-primary-fixed-variant": "#0D5F40",
        "inverse-primary": "#7EB99E",
        "inverse-surface": "#EBE3D1",
        "inverse-on-surface": "#202722",
        secondary: "#167A52",
        "on-secondary": "#FFFFFF",
        "secondary-container": "#DCEAE1",
        "on-secondary-container": "#08452F",
        "secondary-fixed": "#C9E2D5",
        "secondary-fixed-dim": "#167A52",
        "on-secondary-fixed": "#08452F",
        "on-secondary-fixed-variant": "#0D5F40",
        tertiary: "#8A7550",
        "on-tertiary": "#FFFFFF",
        "tertiary-container": "#F1E7D4",
        "on-tertiary-container": "#463A21",
        "tertiary-fixed": "#F1E7D4",
        "tertiary-fixed-dim": "#DFD2B5",
        "on-tertiary-fixed": "#332912",
        "on-tertiary-fixed-variant": "#5B4C2E",
        outline: "#5F6B63",
        "outline-variant": "#E2D8C4",
        error: "#B3261E",
        "on-error": "#FFFFFF",
        "error-container": "#F9DEDC",
        "on-error-container": "#410E0B",
        "signal-green": "#167A52",
        "deep-sage": "#3C6E58",
        "brand-deep": "#0D5F40",
        whiteout: "#FFFFFF",
        haze: "#F6F0E4",
        ink: "#202722",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3.25rem",
        "space-3xl": "5rem",
        "space-4xl": "7.5rem",
        gutter: "1.5rem",
        "gutter-sm": "1rem",
        margin: "3.25rem",
        "margin-mobile": "1rem",
      },
      fontFamily: {
        "headline-xl": ["var(--font-fraunces)", "Fraunces", "Georgia", "serif"],
        "headline-xl-mobile": ["var(--font-fraunces)", "Fraunces", "Georgia", "serif"],
        "headline-lg": ["var(--font-fraunces)", "Fraunces", "Georgia", "serif"],
        "headline-lg-mobile": ["var(--font-fraunces)", "Fraunces", "Georgia", "serif"],
        "headline-md": ["var(--font-fraunces)", "Fraunces", "Georgia", "serif"],
        "headline-sm": ["var(--font-fraunces)", "Fraunces", "Georgia", "serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-sm": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["80px", { lineHeight: "88px", letterSpacing: "0.01em", fontWeight: "800" }],
        "headline-xl-mobile": ["44px", { lineHeight: "50px", letterSpacing: "0.01em", fontWeight: "800" }],
        "headline-lg": ["52px", { lineHeight: "60px", letterSpacing: "0.005em", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "38px", letterSpacing: "0.005em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
