import type { Config } from "tailwindcss";

/**
 * Verbatim transcription of the inline `tailwind.config` embedded in the
 * approved Stitch export (`global_professional_services/code.html`).
 *
 * Verified against all 16 exports: 14 are token-identical; FAQ and
 * Privacy exports are missing their `spacing`/`fontSize` blocks entirely
 * (export drift, not a design decision). DESIGN.md is authoritative for
 * colors/typography/spacing; its radius scale conflicts with the export
 * render, so the export values below win.
 */
const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./lib/**/*.{ts,tsx}", "./data/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1b1b1b",
        "surface-container": "#1f1f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353535",
        "surface-variant": "#353535",
        "surface-tint": "#c6c6c7",
        background: "#131313",
        "on-background": "#e2e2e2",
        "on-surface": "#e2e2e2",
        "on-surface-variant": "#c4c7c8",
        primary: "#ffffff",
        "on-primary": "#2f3131",
        "primary-container": "#e2e2e2",
        "on-primary-container": "#636565",
        "primary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#c6c6c7",
        "on-primary-fixed": "#1a1c1c",
        "on-primary-fixed-variant": "#454747",
        "inverse-primary": "#5d5f5f",
        "inverse-surface": "#e2e2e2",
        "inverse-on-surface": "#303030",
        secondary: "#a9c9f5",
        "on-secondary": "#0c3256",
        "secondary-container": "#28486e",
        "on-secondary-container": "#98b7e3",
        "secondary-fixed": "#d3e4ff",
        "secondary-fixed-dim": "#a9c9f5",
        "on-secondary-fixed": "#001c38",
        "on-secondary-fixed-variant": "#28486e",
        tertiary: "#ffffff",
        "on-tertiary": "#2f3131",
        "tertiary-container": "#e2e2e2",
        "on-tertiary-container": "#636565",
        "tertiary-fixed": "#e2e2e2",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-tertiary-fixed": "#1a1c1c",
        "on-tertiary-fixed-variant": "#454747",
        outline: "#8e9192",
        "outline-variant": "#444748",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "signal-blue": "#2b7fff",
        "twilight-blue": "#426188",
        "black-void": "#000000",
        whiteout: "#ffffff",
        haze: "#f5f5f5",
        ink: "#1b1b1b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3.25rem",
        "space-3xl": "5rem",
        "space-4xl": "7.5rem",
        gutter: "1.5rem",
        "gutter-sm": "1rem",
        margin: "3.25rem",
        "margin-mobile": "1rem",
      },
      fontFamily: {
        "headline-xl": ["var(--font-anton)", "Anton", "sans-serif"],
        "headline-xl-mobile": ["var(--font-anton)", "Anton", "sans-serif"],
        "headline-lg": ["var(--font-anton)", "Anton", "sans-serif"],
        "headline-lg-mobile": ["var(--font-anton)", "Anton", "sans-serif"],
        "headline-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-sm": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["80px", { lineHeight: "84px", letterSpacing: "0.02em", fontWeight: "900" }],
        "headline-xl-mobile": ["44px", { lineHeight: "48px", letterSpacing: "0.02em", fontWeight: "900" }],
        "headline-lg": ["52px", { lineHeight: "56px", letterSpacing: "0.01em", fontWeight: "900" }],
        "headline-lg-mobile": ["32px", { lineHeight: "36px", letterSpacing: "0.01em", fontWeight: "900" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
